version: '3.5'
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql
  web:
    build: .
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    environment:
      - SECRET_KEY=secret
    depends_on:
      - database
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - database
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .\nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
volumes:
  db_volume:

